### ISSUE TITLE
目前cxkitty已经不支持人脸视频了吗

### ISSUE THREAD

**Issue by zzl127** [fuqiuluo/CxKittyForAndroid#1]
2024-11-22 16:00:34,215 [Main] ERROR -> 
-----*程序运行异常退出*-----
Traceback (most recent call last):
![Screenshot_20241122_160047](https://github.com/user-attachments/assets/8f79068e-08b9-43de-b23a-f1bab6d8873b)

  File "/data/user/0/moe.fuqiuluo.xxt/files/cxkitty/main.py", line 372, in <module>
    fuck_task_worker(task_obj)
  File "/data/user/0/moe.fuqiuluo.xxt/files/cxkitty/main.py", line 233, in fuck_task_worker
    resolver.execute()
  File "/data/user/0/moe.fuqiuluo.xxt/files/cxkitty/resolver/media.py", line 75, in execute
    report_result = self.media_dto.play_report(playing_time)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/moe.fuqiuluo.xxt/files/cxkitty/cxapi/task_point/video.py", line 131, in play_report
    resp.raise_for_status()
  File "/data/user/0/moe.fuqiuluo.xxt/files/aarch64-linux-android/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://mooc1-api.chaoxing.com/multimedia/log/a/273162137/60f5246172d73a12980bfd8651e135fd?otherInfo=nodeId_705044055-cpi_273162137-rt_d-ds_0-ff_1-be_0_0-vt_1-v_6-enc_1545e2e31f29aa9752747511c0f6db10&courseId=245983348&playingTime=0&duration=457&jobid=1409302017731&clipTime=0_457&clazzId=105533748&objectId=53ffd36fa3106c27b61ad931&userid=244955941&isdrag=0&enc=abe49ebe68d1b1e6b59fb75cb392ebd2&rt=0.9&dtype=Video&view=pc&_t=1732262433746

**Comment by fuqiuluo** [comment]
这里面用的是一年前的Cxkitty（
